name: lifelog_repo

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  equatable: ^1.1.1
  sqflite: ^1.3.0
  path_provider: ^1.6.18
  path: ^1.7.0